# Generated by Django 3.0.2 on 2020-01-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200123_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
