# Generated by Django 3.0.2 on 2020-01-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200123_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='Summary Here', null=True),
        ),
    ]
