# Generated by Django 3.0.2 on 2020-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200123_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.TextField(),
        ),
    ]
